/**
 * DOMNode property white list
 * Taken from https://github.com/Raynos/react/blob/dom-property-config/src/browser/ui/dom/DefaultDOMPropertyConfig.js
*/

module.exports = {
  "accept": "accept",
  "acceptCharset": "accept-charset",
  "accessKey": "accesskey",
  "action": "action",
  "alt": "alt",
  "async": "async",
  "autoComplete": "autocomplete",
  "autoPlay": "autoplay",
  "cellPadding": "cellpadding",
  "cellSpacing": "cellspacing",
  "charset": "charset",
  "checked": "checked",
  "class": "class",
  "className": "class",
  "colSpan": "colspan",
  "content": "content",
  "contentEditable": "contenteditable",
  "controls": "controls",
  "crossOrigin": "crossorigin",
  "data": "data",
  "defer": "defer",
  "dir": "dir",
  "download": "download",
  "draggable": "draggable",
  "encType": "enctype",
  "formNoValidate": "formnovalidate",
  "href": "href",
  "hrefLang": "hreflang",
  "htmlFor": "htmlfor",
  "httpEquiv": "http-equiv",
  "icon": "icon",
  "id": "id",
  "label": "label",
  "lang": "lang",
  "list": "list",
  "loop": "loop",
  "max": "max",
  "mediaGroup": "mediagroup",
  "method": "method",
  "min": "min",
  "multiple": "multiple",
  "muted": "muted",
  "name": "name",
  "noValidate": "novalidate",
  "pattern": "pattern",
  "placeholder": "placeholder",
  "poster": "poster",
  "preload": "preload",
  "radioGroup": "radiogroup",
  "readOnly": "readonly",
  "rel": "rel",
  "required": "required",
  "rowSpan": "rowspan",
  "sandbox": "sandbox",
  "scope": "scope",
  "scrollLeft": "scrollleft",
  "scrolling": "scrolling",
  "scrollTop": "scrolltop",
  "selected": "selected",
  "span": "span",
  "spellCheck": "spellcheck",
  "src": "src",
  "srcDoc": "srcdoc",
  "srcSet": "srcset",
  "start": "start",
  "step": "step",
  "style": "style",
  "tabIndex": "tabindex",
  "target": "target",
  "title": "title",
  "type": "type",
  "value": "value",

  // Non-standard Properties
  "autoCapitalize": "autocapitalize",
  "autoCorrect": "autocorrect",
  "property": "property",
  "attributes": "attributes",

  // SVG Properties
  "cx": "cx",
  "cy": "cy",
  "d": "d",
  "dx": "dx",
  "dy": "dy",
  "fill": "fill",
  "fx": "fx",
  "fy": "fy",
  "gradientTransform": "gradientTransform",
  "gradientUnits": "gradientUnits",
  "offset": "offset",
  "points": "points",
  "r": "r",
  "rx": "rx",
  "ry": "ry",
  "spreadMethod": "spreadMethod",
  "stopColor": "stop-color",
  "stopOpacity": "stop-opacity",
  "stroke": "stroke",
  "strokeLinecap": "stroke-linecap",
  "strokeWidth": "stroke-width",
  "textAnchor": "text-anchor",
  "transform": "transform",
  "version": "version",
  "viewBox": "viewBox",
  "x1": "x1",
  "x2": "x2",
  "x": "x",
  "y1": "y1",
  "y2": "y2",
  "y": "y"
};
